### ISSUE TITLE
this.request.body doesn't return nothing anymore

### ISSUE THREAD

**Issue by DirkStevens** [EventedMind/iron-router#1190]
Dear @cmather this is a re-open of https://github.com/EventedMind/iron-router/issues/1003 which has been closed since November yet still hasn't been fixed in the latest 1.0.7 release with Meteor 1.0.3.1 ?

Because this.request.body returns {} the application breaks - where it used to work before.

There's been solutions suggested but none have worked for me.  I've reached out to some people in the issue discussion to no avail....

**Comment by matfin** [comment]
I was having similar issues with an empty request body in IronRouter, so I started using npm modules connect and body-parser. 

You can have a look at my Gist here - https://gist.github.com/matfin/14f50d035c01ce333332

**Comment by joaopiopedreira** [comment]
Hi [@cmather](https://github.com/cmather). I'm using Meteor 1.0.3.1 and have the same issue listed above. My server API is now broken. When do you think this could be properly solved in Iron Routes?

Thanks.

**Comment by cmather** [comment]
@DirkStevens, If you can link to a small app with a reproduction I'll take a look. The request.body stuff is a little fragile because I'm using the Connect bodyParser middleware. So each type of content has to be configured independently. json and form posts should be working by now. But if I can run some code that you're seeing it'll help me see a spot I may have missed.

**Comment by DirkStevens** [comment]
Hey @cmather, I just sent you an invite to a private repo which nicely repros the problem.

Hello @matfin,tried to work with your gist but somehow couldn't get it to work either...got nasty complaints with Fiber...

**Comment by travisdahl** [comment]
Similar to @MiroRadenovic's screenshot in https://github.com/EventedMind/iron-router/issues/1003. My nested attributes are no longer available via dot syntax.

I used to be able to access `@request.body.profile.first_name` but now its coming through as a single key instead of nested JSON `'profile[first_name]': 'trav'` so a majority of my code is broken. Is there a  solution for this?

**Comment by DirkStevens** [comment]
@cmather @joaopiopedreira  @matfin @travisdahl thanks to great help from @cmather I've been able to get the "iron router 0.8" behavior back for multipart with a simple multipart package:

Have a look at https://github.com/cmather/meteor-multipart-upload

@travisdahl - I haven't tested this with nested fields.

Note that I submit my form data through an xmlHttpRequest like this:

    var formData = new FormData();
    $.each(files, function(key, value) {
        formData.append(key, value);
    });
    formData.append('id', 'webClient');
    formData.append('api_token', encTok);

    request.open("POST", '/api/upload', true);
    request.send(formData);

Hope this helps.

**Comment by DirkStevens** [comment]
Oh yes - I'm using filereader.js to select file(s) to upload.

**Comment by daslicht** [comment]
files is anytime undefined here :/
