### ISSUE TITLE
Is there a way to have wait() wait on a Meteor.call? In general could it be made more flexible?

### ISSUE THREAD

**Issue by micahblu** [EventedMind/iron-router#1220]
Really love the router, however I find the wait() method to be a quite limiting. Is there a way to extend its functionality so that it could be used with for example a Meteor.call response? Perhaps something similar to how gulp allows asynchronous execution by passing a callback and triggering it when done?

**Comment by copleykj** [comment]
Hi Micha,

Because Iron-Router accomplishes waiting by attaching the ready() state of
a subscription to a dependency computation, I think that it should be
rather simple to implement your own function or class which would make a
method call and return a handle with a reactive ready() function which upon
completion of the method call would reactively run and return true and thus
bringing Iron-Router into a ready state.  Hope this helps

**Comment by micahblu** [comment]
@copleykj that worked brilliantly! Thanks :)

**Comment by copleykj** [comment]
My pleasure :-)
